# Generated by Django 2.1.4 on 2019-01-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarchapp', '0003_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('motto', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='info')),
            ],
            options={
                'verbose_name': 'Site Bilgisi',
                'verbose_name_plural': 'Site Bilgileri',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
