# Generated by Django 2.1.4 on 2019-01-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarchapp', '0004_auto_20190108_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='motto',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
