# Generated by Django 2.1.4 on 2019-01-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarchapp', '0005_auto_20190108_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='introduction_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
